/**
 * GeoLens SynthID Detection Backend
 * POST /verify-image/ — accepts multipart/form-data with a `file` field
 *
 * Uses reverse-SynthID (github.com/aloshdenny/reverse-SynthID) for detection.
 * Credit: reverse-SynthID by Alosh Denny - github.com/aloshdenny/reverse-SynthID
 *
 * Install:
 *   npm install express multer cors dotenv
 *
 * Run:
 *   node SynthID.js
 */

import 'dotenv/config';
import express from 'express';
import multer from 'multer';
import cors from 'cors';
import { writeFile, unlink } from 'fs/promises';
import { tmpdir } from 'os';
import { join, dirname } from 'path';
import { randomUUID } from 'crypto';
import { fileURLToPath } from 'url';
import { spawn } from 'child_process';

const __dirname = dirname(fileURLToPath(import.meta.url));

const app = express();
const upload = multer({ storage: multer.memoryStorage() });
app.use(cors());

// Python interpreter to spawn the detector with. macOS/Homebrew only ships
// `python3`, while the Docker image symlinks `python` — default to `python3`
// and let the container override via env.
const PYTHON_BIN = process.env.PYTHON_BIN ?? 'python3';

// ── Health ──────────────────────────────────────────────────────────────────

app.get('/', (_req, res) => {
  res.json({ message: 'GeoLens SynthID backend running' });
});

// ── Route ─────────────────────────────────────────────────────────────────────

app.post('/verify-image/', upload.single('file'), async (req, res) => {
  if (!req.file) {
    return res.status(400).json({ error: 'No file uploaded' });
  }

  const ext = mimeToExt(req.file.mimetype);
  const tmpPath = join(tmpdir(), `geolens-${randomUUID()}.${ext}`);

  try {
    await writeFile(tmpPath, req.file.buffer);

    const synthid = await checkSynthId(tmpPath);

    return res.json({
      checks: { synthid },
    });
  } catch (err) {
    console.error('[verify-image] error:', err);
    return res.status(500).json({ error: err instanceof Error ? err.message : 'Internal server error' });
  } finally {
    await unlink(tmpPath).catch(() => {});
  }
});

// ── SynthID Check via Python Detector ────────────────────────────────────────

async function checkSynthId(imagePath) {
  return new Promise((resolve) => {
    const scriptPath = join(__dirname, 'detect.py');

    const python = spawn(PYTHON_BIN, [scriptPath, imagePath]);

    let output = '';
    let errorOutput = '';

    python.stdout.on('data', (data) => {
      output += data.toString();
    });

    python.stderr.on('data', (data) => {
      errorOutput += data.toString();
    });

    python.on('close', (code) => {
      try {
        const result = JSON.parse(output.trim());

        if (result.error) {
          resolve({
            status: 'unavailable',
            message: 'SynthID detection failed',
            error: result.error,
          });
          return;
        }

        if (result.watermarked) {
          resolve({
            status: 'not-verified',
            message: `SynthID watermark detected (confidence: ${(result.confidence * 100).toFixed(0)}%)`,
            error: 'This image may have been generated by Google AI.',
          });
        } else {
          resolve({
            status: 'verified',
            message: `No SynthID watermark found (confidence: ${(result.confidence * 100).toFixed(0)}%)`,
            error: 'No Google AI watermark detected.',
          });
        }
      } catch (e) {
        resolve({
          status: 'unavailable',
          message: 'SynthID detection failed',
          error: errorOutput || 'Could not parse detector output',
        });
      }
    });

    // Timeout after 30 seconds
    setTimeout(() => {
      python.kill();
      resolve({
        status: 'unavailable',
        message: 'SynthID detection timed out',
        error: 'The detector took too long to respond.',
      });
    }, 30000);
  });
}

// ── Helpers ───────────────────────────────────────────────────────────────────

function mimeToExt(mime) {
  const map = {
    'image/jpeg': 'jpg',
    'image/png':  'png',
    'image/webp': 'webp',
    'image/tiff': 'tiff',
    'image/avif': 'avif',
    'image/heic': 'heic',
  };
  return map[mime] ?? 'bin';
}

// ── Start ─────────────────────────────────────────────────────────────────────

const PORT = process.env.PORT ?? 8008;
app.listen(PORT, () => {
  console.log(`[GeoLens] backend listening on http://localhost:${PORT}`);
});
